// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUiLQ9Op-h-JSNws117H_28aGYLPHh1n0',
    appId: '1:139717560432:web:a3a344d47dc67df4298cb5',
    messagingSenderId: '139717560432',
    projectId: 'advertisements-5627c',
    authDomain: 'advertisements-5627c.firebaseapp.com',
    storageBucket: 'advertisements-5627c.appspot.com',
    measurementId: 'G-0YYG6JXSN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfyJLLwes-tRcL1CexiTX-CVwaWShbgA',
    appId: '1:139717560432:android:861f350013529818298cb5',
    messagingSenderId: '139717560432',
    projectId: 'advertisements-5627c',
    storageBucket: 'advertisements-5627c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnDS-c43dlh0tJ4zFjE2A_lsq2nIE8UHI',
    appId: '1:139717560432:ios:5189c23d7c115404298cb5',
    messagingSenderId: '139717560432',
    projectId: 'advertisements-5627c',
    storageBucket: 'advertisements-5627c.appspot.com',
    iosBundleId: 'example.ads.advertisements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnDS-c43dlh0tJ4zFjE2A_lsq2nIE8UHI',
    appId: '1:139717560432:ios:5189c23d7c115404298cb5',
    messagingSenderId: '139717560432',
    projectId: 'advertisements-5627c',
    storageBucket: 'advertisements-5627c.appspot.com',
    iosBundleId: 'example.ads.advertisements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUiLQ9Op-h-JSNws117H_28aGYLPHh1n0',
    appId: '1:139717560432:web:09fadf26f9199aec298cb5',
    messagingSenderId: '139717560432',
    projectId: 'advertisements-5627c',
    authDomain: 'advertisements-5627c.firebaseapp.com',
    storageBucket: 'advertisements-5627c.appspot.com',
    measurementId: 'G-S255B8S0TR',
  );
}
